-- Neighbourhood directory: per-compound places, two tiers, code-unlocked vetted layer.
-- Run top to bottom in the Supabase SQL editor. Safe to re-run.

-- ============================================================
-- compounds
-- ============================================================
create table if not exists public.compounds (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name_en text not null,
  name_ar text not null,
  location text not null,
  -- Listing names that belong to this compound, e.g. {'Hacienda bay','Hacienda Bay'}.
  -- The site owns this mapping explicitly so the web and the iOS app don't each
  -- parse listing names independently and drift apart.
  match_names text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists compounds_slug_idx on public.compounds (slug);

-- ============================================================
-- places
-- ============================================================
create table if not exists public.places (
  id uuid primary key default gen_random_uuid(),
  compound_id uuid not null references public.compounds (id) on delete cascade,
  category text not null,
  name_en text not null,
  name_ar text not null default '',
  phone text,
  whatsapp text,
  address text,
  lat numeric,
  lng numeric,
  -- 'public' needs no code. 'vetted' is GOLD's own trusted trades and is only
  -- ever returned by the unlock endpoint, never by the public places endpoint.
  tier text not null default 'public' check (tier in ('public', 'vetted')),
  notes_en text not null default '',
  notes_ar text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists places_compound_idx on public.places (compound_id);
create index if not exists places_tier_idx on public.places (compound_id, tier, active);

-- ============================================================
-- compound_codes
-- ============================================================
create table if not exists public.compound_codes (
  id uuid primary key default gen_random_uuid(),
  compound_id uuid not null references public.compounds (id) on delete cascade,
  code text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  rotated_at timestamptz
);
-- Rotating issues a new code and deactivates the old one for NEW redemptions;
-- devices that already redeemed keep access via their existing redemption row.
-- A guest mid-stay must not lose the plumber's number because staff tidied up.
create index if not exists compound_codes_lookup_idx on public.compound_codes (code) where active;

-- ============================================================
-- redemptions
-- ============================================================
create table if not exists public.redemptions (
  id uuid primary key default gen_random_uuid(),
  code_id uuid not null references public.compound_codes (id) on delete cascade,
  -- Random UUID generated by the app and kept in the Keychain. Not a name, phone,
  -- or advertising id -- it exists only to count usage and revoke an over-shared code.
  device_id text not null,
  redeemed_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (code_id, device_id)
);
create index if not exists redemptions_code_idx on public.redemptions (code_id);

-- ============================================================
-- Row level security
-- ============================================================
-- Same posture as public.properties: every read goes through the server-side
-- service role, so RLS stays enabled with no public policies. None of these
-- tables is reachable from a browser or a mobile binary using the anon key.
alter table public.compounds enable row level security;
alter table public.places enable row level security;
alter table public.compound_codes enable row level security;
alter table public.redemptions enable row level security;
